name: Code Coverage

on:
    pull_request: null

jobs:
    code_coverage:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: pcov
                    tools: composer:v2

            -
                run: composer install --no-progress --ansi

            # https://kizu514.com/blog/pcov-is-better-than-phpdbg-and-xdebug-for-code-coverage/
            -
                run: |
                    #composer require --dev nimut/phpunit-merger

                    #vendor/bin/phpunit --coverage-php build/logs/rules.cov --testsuite rules
                    #vendor/bin/phpunit --coverage-php build/logs/packages.cov --testsuite packages
                    #vendor/bin/phpunit --coverage-php build/logs/tests.cov --testsuite tests
                    #vendor/bin/phpunit --coverage-php build/logs/utils.cov --testsuite utils

                    #vendor/bin/phpunit-merger coverage build/logs clover.xml

                    vendor/bin/phpunit --coverage-clover build/logs/clover.xml

                    # Coveralls.io
                    composer require --dev php-coveralls/php-coveralls:^2.4
                    vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
