name: Code Coverage

on:
    pull_request: null

jobs:
    code_coverage:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: pcov
                    tools: composer:v2

            -
                run: composer install --no-progress --ansi

            # https://kizu514.com/blog/pcov-is-better-than-phpdbg-and-xdebug-for-code-coverage/
            -
                run: |
                    wget https://phar.phpunit.de/phpcov.phar

                    vendor/bin/phpunit --coverage-clover build/logs/rules.xml --testsuite rules
                    vendor/bin/phpunit --coverage-clover build/logs/packages.xml --testsuite packages
                    vendor/bin/phpunit --coverage-clover build/logs/tests.xml --testsuite tests
                    vendor/bin/phpunit --coverage-clover build/logs/utils.xml --testsuite utils

                    ./phpcov.phar merge --clover clover.xml build/logs

                    # Coveralls.io
                    composer require --dev php-coveralls/php-coveralls:^2.4
                    vendor/bin/php-coveralls --coverage_clover=clover.xml -v
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
