name: Code Coverage

on:
    pull_request: null

jobs:
    code_coverage:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: pcov
                    tools: composer:v2

            -
                run: composer install --no-progress --ansi

            # https://kizu514.com/blog/pcov-is-better-than-phpdbg-and-xdebug-for-code-coverage/
            -
                run: |
                    wget https://phar.phpunit.de/phpcov.phar
                    chmod +x ./phpcov.phar

                    echo "testing rules"
                    vendor/bin/phpunit --coverage-php build/logs/rules.cov --testsuite rules

                    echo "testing packages"
                    vendor/bin/phpunit --coverage-php build/logs/packages.cov --testsuite packages

                    echo "testing tests"
                    vendor/bin/phpunit --coverage-php build/logs/tests.cov --testsuite tests

                    #echo "testing utils"
                    #vendor/bin/phpunit --coverage-php build/logs/utils.cov --testsuite utils

                    ./phpcov.phar merge --clover clover.xml build/logs

                    # Coveralls.io
                    composer require --dev php-coveralls/php-coveralls:^2.4
                    vendor/bin/php-coveralls --coverage_clover=clover.xml -v
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
